### ISSUE TITLE
unable to get the world in gazebo

### ISSUE THREAD

**Issue by gopidusanapudi** [SebastianBitsch/gazebo_satellite_terrain#1]
After all the modifications it showing 
some errors in code 
in this i give mapbox key ,username , stylename

[ERROR] [launch]: Caught exception in launch (see debug for traceback): Caught multiple exceptions when trying to load file of format [py]:
 - ValueError: dictionary update sequence element #3 has length 1; 2 is required
 - InvalidFrontendLaunchFileError: The launch file may have a syntax error, or its format is unknown

and i also saw some releated to you there also iam not getting following this : https://classic.gazebosim.org/tutorials?tut=static_map_plugin&cat=build_world (in this am using google api key)
for both are tested in ubuntu 22
can you give solution to this some what iget in above is refer 
![default_gzclient_camera(1)-2024-09-09T10_18_23 134793](https://github.com/user-attachments/assets/f1cd9ca1-fcda-4327-b9d1-d90723ecc2ef)

**Comment by SebastianBitsch** [comment]
Hi,

It sounds like the error could be in the `load_env()` function that reads the environment variables, perhaps because of a colon in your `.env` file, can you please confirm that the file is on the form below and that there are no colons in the file:
```
MAPBOX_APIKEY=<your_key>
MAPBOX_USERNAME=<your_name>
MAPBOX_STYLENAME=<your_style>
```
and not 
```
MAPBOX_APIKEY:<your_key>
MAPBOX_USERNAME:<your_name>
MAPBOX_STYLENAME:<your_style>
```
Alternatively try commenting out `load_env(path = env_path)` in the launch file and just manually writing the environment variables to the env.

Let me know if it helps, thanks

**Comment by gopidusanapudi** [comment]
~/testing/gazebo_satellite_terrain$ ros2 launch gazebo_satellite_terrain launch_sim.launch.py
[INFO] [launch]: All log files can be found below /home/boson-253/.ros/log/2024-09-09-15-51-05-174295-bml-ap-253-79173
[INFO] [launch]: Default logging verbosity is set to INFO
/home/boson-253/testing/gazebo_satellite_terrain/install/gazebo_satellite_terrain/share/gazebo_satellite_terrain/.env
/home/boson-253/testing/gazebo_satellite_terrain/install/gazebo_satellite_terrain/share/gazebo_satellite_terrain
[ERROR] [launch]: Caught exception in launch (see debug for traceback): Caught multiple exceptions when trying to load file of format [py]:
 - 
MAPBOX_APIKEY=<your_key>
MAPBOX_USERNAME=<your_name>
MAPBOX_STYLENAME=<your_style>

 use this format only 
issue not solved same repeating

**Comment by SebastianBitsch** [comment]
Hi again,

Sorry I am having a hard time debugging your issue from that output - also you seem to have edited your answer multiple times and have a different error than the one previously? 
Can you send the contents of the most recent log file in `.ros/log/` 

Thanks

**Comment by gopidusanapudi** [comment]
Hi , sorry for previous mis communications of my logs i solved some but after that following errors are come out i share some of the logs below 
 
[terrain-1] [INFO] [1725940186.357160558] [TerrainManager]: TileSpawner: Error downloading image: 401: Unauthorized
[terrain-1] file download dir /home/boson-253/gazebo_ws/install/gazebo_satellite_terrain/share/gazebo_satellite_terrain/models/satellite_tile/materials/textures/tile_140212_81956.jpeg
[terrain-1] file download dir /home/boson-253/gazebo_ws/install/gazebo_satellite_terrain/share/gazebo_satellite_terrain/models/satellite_tile/materials/textures/tile_140212_81957.jpeg
[terrain-1] file download dir /home/boson-253/gazebo_ws/install/gazebo_satellite_terrain/share/gazebo_satellite_terrain/models/satellite_tile/materials/textures/tile_140212_81958.jpeg
[terrain-1] file download dir /home/boson-253/gazebo_ws/install/gazebo_satellite_terrain/share/gazebo_satellite_terrain/models/satellite_tile/materials/textures/tile_140212_81959.jpeg
[terrain-1] [INFO] [1725940186.776228597] [TerrainManager]: TileSpawner: Error downloading image: 401: Unauthorized
[terrain-1] [INFO] [1725940186.777043690] [TerrainManager]: TerrainManager: Done fetching tiles
[terrain-1] [INFO] [1725940186.777774230] [TerrainManager]: TerrainManager: Spawning 81 tiles, please wait
[terrain-1] [INFO] [1725940206.489471560] [TerrainManager]: TerrainManager: Done spawning tiles

**Comment by SebastianBitsch** [comment]
Hi,

The error indicates that your API key was bad. 401: Unauthorized means you probably didn't set the API key from Mapbox correctly, see [this page](https://docs.mapbox.com/help/getting-started/access-tokens/) on how to generate one. Also note that you should wrap the key in " or ' in the `.env` file.

**Comment by gopidusanapudi** [comment]
Hi,
Now i am getting the satellite map in gazebo and also save the world 
i have  robot model and bring that into  the saved satellite world which i saved a small world with map size 9 and the robot is moving with the rqt 
now the problem is when i saved a large world with satelllite map size 19 the robot is moving to slow  in large world why i cant understand ,
what is the solution for it .

**Comment by SebastianBitsch** [comment]
Glad to hear everything is working.
If your computer is struggling to handle larger worlds, it is because your machine isn't powerful enough to handle the number of objects (`19*19=361`) in Gazebo. 

You could try changing the `zoom` as set In `config.yaml`. That way each tile will take up a larger geographical area, thereby lowering the total number of Gazebo objects you would need to spawn to cover the area - this of course comes with the drawback of lowering the resolution. See [OSM](https://wiki.openstreetmap.org/wiki/Zoom_levels) for info on zoom level.

I will close this issue here, as this isn't directly related to the package but to your machine

Thanks
